"""change tag schema

Revision ID: 8b86fceb57fa
Revises: 8d4035c77bae
Create Date: 2022-08-05 12:17:45.526326

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b86fceb57fa'
down_revision = '8d4035c77bae'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('record_book_tag_mapping', sa.Column('tag', sa.String(length=70), nullable=False))
    op.drop_constraint('record_book_tag_mapping_tag_id_fkey', 'record_book_tag_mapping', type_='foreignkey')
    op.drop_column('record_book_tag_mapping', 'tag_id')
    op.add_column('record_tag_mapping', sa.Column('tag', sa.String(length=70), nullable=False))
    op.drop_constraint('record_tag_mapping_tag_id_fkey', 'record_tag_mapping', type_='foreignkey')
    op.drop_column('record_tag_mapping', 'tag_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('record_tag_mapping', sa.Column('tag_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.create_foreign_key('record_tag_mapping_tag_id_fkey', 'record_tag_mapping', 'tag', ['tag_id'], ['id'])
    op.drop_column('record_tag_mapping', 'tag')
    op.add_column('record_book_tag_mapping', sa.Column('tag_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.create_foreign_key('record_book_tag_mapping_tag_id_fkey', 'record_book_tag_mapping', 'tag', ['tag_id'], ['id'])
    op.drop_column('record_book_tag_mapping', 'tag')
    # ### end Alembic commands ###
