"""add unique constraint for username and email

Revision ID: 8d4035c77bae
Revises: 70cef025730a
Create Date: 2022-08-02 12:57:07.567497

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '8d4035c77bae'
down_revision = '70cef025730a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_user_username', 'user', ['username'])
    op.create_unique_constraint('uq_user_email', 'user', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_user_username', 'user', type_='unique')
    op.drop_constraint('uq_user_email', 'user', type_='unique')
    # ### end Alembic commands ###
