"""alter columns autogenerated

Revision ID: 70cef025730a
Revises: 14c6562f198a
Create Date: 2022-08-01 18:29:32.652732

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70cef025730a'
down_revision = '14c6562f198a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('record', 'record_book_id',
               existing_type=sa.VARCHAR(length=70),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('record_book', 'user_id',
               existing_type=sa.VARCHAR(length=70),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('user', 'salt',
               existing_type=sa.VARCHAR(length=70),
               type_=sa.String(length=100),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'salt',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=70),
               nullable=True)
    op.alter_column('record_book', 'user_id',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=70),
               existing_nullable=False)
    op.alter_column('record', 'record_book_id',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=70),
               existing_nullable=False)
    # ### end Alembic commands ###
